<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="xavbot">

  <xacro:macro name="xavbot_platform" params="prefix='' mesh_dir='package://xavbot_description/meshes' ">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="1.0" /> <!-- arbitrary value for base mass -->
    <xacro:property name="base_width" value="0.22" />
    <xacro:property name="base_length" value="0.21" />
    <xacro:property name="base_height" value="0.05" />
    <xacro:property name="wheel_mass" value="0.02" /> <!-- arbitrary value for wheel mass -->
    <xacro:property name="wheel_length" value="0.024" />
    <xacro:property name="wheel_radius" value="0.0185" />

    <!-- Base Link -->
    <link name="${prefix}base_link">
      <collision>
        <origin xyz="${base_length / 2} ${base_width / 2} ${wheel_radius + 0.005}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_length} ${base_width} ${2 * wheel_radius + 0.01}"/>
        </geometry>
      </collision>

      <collision>
        <origin xyz="0.095 0.08 0.06" rpy="0 0 0"/>
          <geometry>
            <box size="0.16 0.16 0.025"/>
          </geometry>
      </collision>

      <collision>
        <origin xyz="0.075 0.08 0.1125" rpy="0 0 0"/>
          <geometry>
            <box size="0.12 0.16 0.08"/>
          </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${wheel_radius + 0.00495} " rpy="0 0 0"/>
        <geometry>
          <mesh filename="${mesh_dir}/base.dae"/>
        </geometry>
      </visual>
    </link>

    <!-- front left wheel link -->
    <joint name="${prefix}front_left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_left_wheel"/>
      <origin xyz="${base_length - 0.03} ${base_width} ${wheel_radius}" rpy="-${PI/2} ${PI} 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="${prefix}front_left_wheel">
      <collision>
        <origin xyz="0 0 ${wheel_length / 2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${mesh_dir}/mecanum_simple.dae"/>
        </geometry>
      </visual>
    </link>

    <!-- front right wheel link -->
    <joint name="${prefix}front_right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}front_right_wheel"/>
      <origin xyz="${base_length - 0.03} 0 ${wheel_radius}" rpy="${PI/2} 0 0"/>
      <axis xyz="0 0 -1"/>
    </joint>

    <link name="${prefix}front_right_wheel">
      <collision>
        <origin xyz="0 0 ${wheel_length / 2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${mesh_dir}/mecanum_simple.dae"/>
        </geometry>

      </visual>
    </link>

    <!-- rear left wheel link -->
    <joint name="${prefix}rear_left_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}rear_left_wheel"/>
      <origin xyz="0.03 ${base_width} ${wheel_radius}" rpy="-${PI/2} ${PI} 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <link name="${prefix}rear_left_wheel">
      <collision>
        <origin xyz="0 0 ${wheel_length / 2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${mesh_dir}/mecanum_simple.dae"/>
        </geometry>
      </visual>
    </link>

    <!-- rear right wheel link -->
    <joint name="${prefix}rear_right_wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}rear_right_wheel"/>
      <origin xyz="0.03 0 ${wheel_radius}" rpy="${PI/2} 0 0"/>
      <axis xyz="0 0 -1"/>
    </joint>

    <link name="${prefix}rear_right_wheel">
      <collision>
        <origin xyz="0 0 ${wheel_length / 2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="${mesh_dir}/mecanum_simple.dae"/>
        </geometry>
      </visual>
    </link>

    <!-- lidar -->
    <joint name="${prefix}lidar_joint" type="continuous">
     <parent link="${prefix}base_link"/>
      <child link="${prefix}lidar"/>
      <origin xyz="0.08 0.08 0.135" rpy="0 0 ${PI}"/>
      <axis xyz="0 0 -1"/>
    </joint>

    <link name="${prefix}lidar"/>

  </xacro:macro>

</robot>